version: '3'
services:
 web:
  image: smartlizzard/myfirstapp:latest
  #build:
  #  context: .
  #  dockerfile: Dockerfile
  ports:
   - "3000:3000"
  volumes:
   - /app/node_modules
   - .:/app 
 tests:
  image: smartlizzard/myfirstapp:latest
  #build: 
  #  context: .
  #  dockerfile: Dockerfile
  volumes:
    - /app/node_modules
    - .:/app
  command: ["npm", "run", "test"]
